In [1]:
# Install library
!pip install sentence-transformers

# Import libraries
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [2]:
# Sample sentences from different domains
sentences = [
    "Virat Kohli scored a century in the match",
    "India won the cricket match comfortably",
    "Cybersecurity protects systems from attacks",
    "Hackers use malware to exploit vulnerabilities",
    "Cooking pasta requires boiling water",
    "Italian food is known for pasta and pizza"
]

# Load model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Generate embeddings
embeddings = model.encode(sentences)

print("Embedding shape:", embeddings.shape)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding shape: (6, 384)


In [3]:
# Compute cosine similarity
similarity_matrix = cosine_similarity(embeddings)

# Display similarity matrix
print("Cosine Similarity Matrix:\n")
print(np.round(similarity_matrix, 2))

Cosine Similarity Matrix:

[[ 1.    0.51  0.05  0.09  0.01 -0.03]
 [ 0.51  1.    0.05  0.   -0.04 -0.05]
 [ 0.05  0.05  1.    0.51 -0.03 -0.01]
 [ 0.09  0.    0.51  1.    0.12  0.1 ]
 [ 0.01 -0.04 -0.03  0.12  1.    0.43]
 [-0.03 -0.05 -0.01  0.1   0.43  1.  ]]


In [4]:
# Find most similar sentences
for i in range(len(sentences)):
    similarities = similarity_matrix[i]
    most_similar_index = similarities.argsort()[-2]  # second highest (excluding itself)

    print(f"\nSentence: {sentences[i]}")
    print(f"Most similar: {sentences[most_similar_index]}")


Sentence: Virat Kohli scored a century in the match
Most similar: India won the cricket match comfortably

Sentence: India won the cricket match comfortably
Most similar: Virat Kohli scored a century in the match

Sentence: Cybersecurity protects systems from attacks
Most similar: Hackers use malware to exploit vulnerabilities

Sentence: Hackers use malware to exploit vulnerabilities
Most similar: Cybersecurity protects systems from attacks

Sentence: Cooking pasta requires boiling water
Most similar: Italian food is known for pasta and pizza

Sentence: Italian food is known for pasta and pizza
Most similar: Cooking pasta requires boiling water
